name: Publish package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://npm.pkg.github.com'
          scope: '@melhorenvio'
          cache: 'npm'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_TOKEN_PKG_WRITER }}
